project:
  type: website

website:
  page-navigation: false
  back-to-top-navigation: true
  site-url: https://iqb-specifications.github.io/
  favicon: favicon.ico
  repo-url: https://github.com/iqb-specifications/iqb-specifications.github.io/
  title: "IQB-Spezifikationen"
  navbar:
    pinned: true
    search: true
    logo: assets/iqb-logo-only-white.png
  page-footer:
    border: true
    background: light
    right:
      - text: "IQB 2025"
        href: https://www.iqb.hu-berlin.de
    left:
      - href: index.qmd
        text: "{{< fa house >}}"
  sidebar: 
    style: "docked"
    search: true
    lang: de
    collapse-level: 1
    contents:
      - intro.qmd
format:
  html:
    theme:
      - cyborg
      - custom.scss
    anchor-sections: true
    link-external-newwindow: true
    